import 'package:flutter/material.dart';

const Color primaryColor = Color(0xffFF3B30);
const Color bgColor = Color(0xffFAFAFA);
const Color blackColor = Color(0xff1D2939);
const Color whiteColor = Color(0xffFFFFFF);
const Color successColor = Color(0xff65C18C);
const Color yellowColor = Color(0xffFFC300);
const Color borderColor = Color(0xffEAECF0);
const Color warningColor = Color(0xffF05454);
const Color greyPrimary = Color(0xff1D2939);
const Color greyParagraph = Color(0xff667085);
const Color greyThree = Color(0xff344054);
const Color greyFour = Color(0xff475467);
const Color greyFive = Color(0xffD0D5DD);
const Color dividerColor = Color(0xffF0F0F0);
const Color greySecondary = Color.fromARGB(255, 240, 241, 244);
final inputFieldBorderColor = Colors.grey.withOpacity(.4);
const Color blackCustomColor = Color(0xff1D2939);
const Color orangeColor = Color(0xffFF9F29);
