import 'const_strings.dart';

var translateStrings = {
  ConstString.welcome: ConstString.welcome,
  ConstString.loginToContinue: ConstString.loginToContinue,
  ConstString.emailOrUsername: ConstString.emailOrUsername,
  ConstString.plzEnterYourEmail: ConstString.plzEnterYourEmail,
  ConstString.email: ConstString.email,
  ConstString.pass: ConstString.pass,
  ConstString.plzEnterPass: ConstString.plzEnterPass,
  ConstString.settingShipChargePlzWait: ConstString.settingShipChargePlzWait,
  ConstString.plzWaitOrderProcessed: ConstString.plzWaitOrderProcessed,
  ConstString.enterPass: ConstString.enterPass,
  ConstString.rememberMe: ConstString.rememberMe,
  ConstString.forgotPass: ConstString.forgotPass,
  ConstString.login: ConstString.login,
  ConstString.donotHaveAccount: ConstString.donotHaveAccount,
  ConstString.register: ConstString.register,
  ConstString.changePass: ConstString.changePass,
  ConstString.enterCurrentPass: ConstString.enterCurrentPass,
  ConstString.enterYourCurrentPass: ConstString.enterYourCurrentPass,
  ConstString.enterNewPass: ConstString.enterNewPass,
  ConstString.newPass: ConstString.newPass,
  ConstString.repeatNewPass: ConstString.repeatNewPass,
  ConstString.plzRetypePass: ConstString.plzRetypePass,
  ConstString.retypeNewPass: ConstString.retypeNewPass,
  ConstString.passMustBeSix: ConstString.passMustBeSix,
  ConstString.resetPass: ConstString.resetPass,
  ConstString.enterEmailToGetInstruction:
      ConstString.enterEmailToGetInstruction,
  ConstString.enterEmail: ConstString.enterEmail,
  ConstString.sendInstruction: ConstString.sendInstruction,
  ConstString.enterFourDigit: ConstString.enterFourDigit,
  ConstString.enterFourDigitToResetPass: ConstString.enterFourDigitToResetPass,
  ConstString.didntReceive: ConstString.enterFourDigitToResetPass,
  ConstString.sendAgain: ConstString.sendAgain,
  ConstString.newPassShouldBeDifferent: ConstString.newPassShouldBeDifferent,
  ConstString.chooseCountry: ConstString.chooseCountry,
  ConstString.chooseStates: ConstString.chooseStates,
  ConstString.fullName: ConstString.fullName,
  ConstString.plzEnterFullName: ConstString.plzEnterFullName,
  ConstString.enterFullName: ConstString.enterFullName,
  ConstString.userName: ConstString.userName,
  ConstString.plzEnterUsername: ConstString.plzEnterUsername,
  ConstString.enterUsername: ConstString.enterUsername,
  ConstString.verifyEmail: ConstString.verifyEmail,
  ConstString.enterFourDigitToVerifyEmail:
      ConstString.enterFourDigitToVerifyEmail,
  ConstString.phone: ConstString.phone,
  ConstString.confirmPass: ConstString.confirmPass,
  ConstString.retypePass: ConstString.retypePass,
  ConstString.haveAccount: ConstString.haveAccount,
  ConstString.signIn: ConstString.signIn,
  ConstString.phoneNumber: ConstString.phoneNumber,
  ConstString.enterPhoneNumber: ConstString.enterPhoneNumber,
  ConstString.signUpToContinue: ConstString.signUpToContinue,
  ConstString.city: ConstString.city,
  ConstString.plzEnterYourCity: ConstString.plzEnterYourCity,
  ConstString.enterYourCity: ConstString.enterYourCity,
  ConstString.iAgreeTerms: ConstString.iAgreeTerms,
  ConstString.signUp: ConstString.signUp,
  ConstString.mustAgreeTermsToRegister: ConstString.mustAgreeTermsToRegister,
  ConstString.passDidntMatch: ConstString.passDidntMatch,
  ConstString.mustEnterPhone: ConstString.mustEnterPhone,
  ConstString.alreadyHaveAccount: ConstString.alreadyHaveAccount,
  ConstString.saleCampaign: ConstString.saleCampaign,
  ConstString.days: ConstString.days,
  ConstString.hours: ConstString.hours,
  ConstString.minutes: ConstString.minutes,
  ConstString.seconds: ConstString.seconds,
  ConstString.couponCode: ConstString.couponCode,
  ConstString.enterCouponCode: ConstString.enterCouponCode,
  ConstString.apply: ConstString.apply,
  ConstString.shippingOption: ConstString.shippingOption,
  ConstString.addDeliveryAddress: ConstString.addDeliveryAddress,
  ConstString.cart: ConstString.cart,
  ConstString.subtotal: ConstString.subtotal,
  ConstString.deleteAccount: ConstString.deleteAccount,
  ConstString.discount: ConstString.discount,
  ConstString.vat: ConstString.vat,
  ConstString.shipping: ConstString.shipping,
  ConstString.total: ConstString.total,
  ConstString.checkout: ConstString.checkout,
  ConstString.shippingName: ConstString.shippingName,
  ConstString.plzEnterShippingName: ConstString.plzEnterShippingName,
  ConstString.enterShippingName: ConstString.enterShippingName,
  ConstString.mustSelectCountryState: ConstString.mustSelectCountryState,
  ConstString.plzEnterCouponFirst: ConstString.plzEnterCouponFirst,
  ConstString.plzSelectCountryState: ConstString.plzSelectCountryState,
  ConstString.nothingInCartAddFromStore: ConstString.nothingInCartAddFromStore,
  ConstString.emptyCart: ConstString.emptyCart,
  ConstString.plzEnterDeliveryAndSave: ConstString.plzEnterDeliveryAndSave,
  ConstString.discover: ConstString.discover,
  ConstString.favourite: ConstString.favourite,
  ConstString.nothingInWishlist: ConstString.nothingInWishlist,
  ConstString.nothingInWishlistAddFromStore:
      ConstString.nothingInWishlistAddFromStore,
  ConstString.hi: ConstString.hi,
  ConstString.couldNotLoadProfileInfo: ConstString.couldNotLoadProfileInfo,
  ConstString.seeAll: ConstString.seeAll,
  ConstString.allCategories: ConstString.allCategories,
  ConstString.searchProducts: ConstString.searchProducts,
  ConstString.home: ConstString.home,
  ConstString.likes: ConstString.likes,
  ConstString.menu: ConstString.menu,
  ConstString.skip: ConstString.skip,
  ConstString.continueText: ConstString.continueText,
  ConstString.orderDetails: ConstString.orderDetails,
  ConstString.couponDiscount: ConstString.couponDiscount,
  ConstString.tax: ConstString.tax,
  ConstString.shippingCost: ConstString.shippingCost,
  ConstString.paymentMethod: ConstString.paymentMethod,
  ConstString.areYouSure: ConstString.areYouSure,
  ConstString.cancel: ConstString.cancel,
  ConstString.yes: ConstString.yes,
  ConstString.products: ConstString.products,
  ConstString.quantity: ConstString.quantity,
  ConstString.refund: ConstString.refund,
  ConstString.plzEnterPhone: ConstString.plzEnterPhone,
  ConstString.cityTown: ConstString.cityTown,
  ConstString.plzEnterCityTown: ConstString.plzEnterCityTown,
  ConstString.enterCityTown: ConstString.enterCityTown,
  ConstString.zipCode: ConstString.zipCode,
  ConstString.plzEnterZip: ConstString.plzEnterZip,
  ConstString.enterZip: ConstString.enterZip,
  ConstString.address: ConstString.address,
  ConstString.plzEnterAddress: ConstString.plzEnterAddress,
  ConstString.enterAddress: ConstString.enterAddress,
  ConstString.minimum: ConstString.minimum,
  ConstString.orderIsNeeded: ConstString.orderIsNeeded,
  ConstString.couponNeeded: ConstString.couponNeeded,
  ConstString.noShippingAvailable: ConstString.noShippingAvailable,
  ConstString.save: ConstString.save,
  ConstString.plzSelectState: ConstString.plzSelectState,
  ConstString.myOrders: ConstString.myOrders,
  ConstString.details: ConstString.details,
  ConstString.order: ConstString.order,
  ConstString.payment: ConstString.payment,
  ConstString.oops: ConstString.oops,
  ConstString.orderFailed: ConstString.orderFailed,
  ConstString.backToHome: ConstString.backToHome,
  ConstString.orderSuccessful: ConstString.orderSuccessful,
  ConstString.orderPlacedIdIs: ConstString.orderPlacedIdIs,
  ConstString.seeOrderDetails: ConstString.seeOrderDetails,
  ConstString.choosePayMethod: ConstString.choosePayMethod,
  ConstString.chooseImages: ConstString.chooseImages,
  ConstString.payConfirmOrder: ConstString.payConfirmOrder,
  ConstString.youMustAgreeTerms: ConstString.youMustAgreeTerms,
  ConstString.privacyPolicy: ConstString.privacyPolicy,
  ConstString.termsCondition: ConstString.termsCondition,
  ConstString.featuredProducts: ConstString.featuredProducts,
  ConstString.writeReview: ConstString.writeReview,
  ConstString.buyNow: ConstString.buyNow,
  ConstString.youMustSelectAllAttr: ConstString.youMustSelectAllAttr,
  ConstString.addToCart: ConstString.addToCart,
  ConstString.inStock: ConstString.inStock,
  ConstString.outOfStock: ConstString.outOfStock,
  ConstString.howWasProduct: ConstString.howWasProduct,
  ConstString.postReview: ConstString.postReview,
  ConstString.allFeaturedProducts: ConstString.allFeaturedProducts,
  ConstString.noProductFound: ConstString.noProductFound,
  ConstString.desc: ConstString.desc,
  ConstString.review: ConstString.review,
  ConstString.shipAndReturn: ConstString.shipAndReturn,
  ConstString.priority: ConstString.priority,
  ConstString.status: ConstString.status,
  ConstString.createTicket: ConstString.createTicket,
  ConstString.title: ConstString.title,
  ConstString.plzEnterTicketTitle: ConstString.plzEnterTicketTitle,
  ConstString.ticketTitle: ConstString.ticketTitle,
  ConstString.subject: ConstString.subject,
  ConstString.plzEnterTicketSubject: ConstString.plzEnterTicketSubject,
  ConstString.describeYourProb: ConstString.describeYourProb,
  ConstString.writeMessage: ConstString.writeMessage,
  ConstString.plzWriteMessageFirst: ConstString.plzWriteMessageFirst,
  ConstString.refundTickets: ConstString.refundTickets,
  ConstString.create: ConstString.create,
  ConstString.noTicketFound: ConstString.noTicketFound,
  ConstString.pending: ConstString.pending,
  ConstString.refundProducts: ConstString.refundProducts,
  ConstString.orderId: ConstString.orderId,
  ConstString.date: ConstString.date,
  ConstString.amount: ConstString.amount,
  ConstString.completed: ConstString.completed,
  ConstString.filterBy: ConstString.filterBy,
  ConstString.category: ConstString.category,
  ConstString.subCategory: ConstString.subCategory,
  ConstString.childCategory: ConstString.childCategory,
  ConstString.minPrice: ConstString.minPrice,
  ConstString.enterMinPrice: ConstString.enterMinPrice,
  ConstString.enterMaxPrice: ConstString.enterMaxPrice,
  ConstString.ratings: ConstString.ratings,
  ConstString.clear: ConstString.clear,
  ConstString.search: ConstString.search,
  ConstString.memberSince: ConstString.memberSince,
  ConstString.country: ConstString.country,
  ConstString.logout: ConstString.logout,
  ConstString.editProfile: ConstString.editProfile,
  ConstString.changePhoto: ConstString.changePhoto,
  ConstString.updatingProfileMayTakeFewSec:
      ConstString.updatingProfileMayTakeFewSec,
  ConstString.supportTickets: ConstString.supportTickets,
  ConstString.shippingAddress: ConstString.shippingAddress,
  ConstString.notLoggedIn: ConstString.notLoggedIn,
  ConstString.accountInfoNotAvailable: ConstString.accountInfoNotAvailable,
  ConstString.delete: ConstString.delete,
  ConstString.viewDetails: ConstString.viewDetails,
  ConstString.removeFromFav: ConstString.removeFromFav,
  ConstString.qtyIncreased: ConstString.qtyIncreased,
  ConstString.priceRange: ConstString.priceRange,
  ConstString.selectCountry: ConstString.selectCountry,
  ConstString.selectCity: ConstString.selectCity,
  ConstString.noCountryFound: ConstString.noCountryFound,
  ConstString.searchCountry: ConstString.searchCountry,
  ConstString.searchState: ConstString.searchState,
  ConstString.noCityFound: ConstString.noCityFound,
  ConstString.addedToCart: ConstString.addedToCart,
  ConstString.youDontHaveAddressSaved: ConstString.youDontHaveAddressSaved,
  ConstString.addOrReplaceAddress: ConstString.addOrReplaceAddress,
  ConstString.department: ConstString.department,
  ConstString.recentProducts: ConstString.recentProducts,
  ConstString.allRecentProducts: ConstString.allRecentProducts,
  ConstString.maxPrice: ConstString.maxPrice,
  ConstString.youAlreadyAppliedThisCoupon:
      ConstString.youAlreadyAppliedThisCoupon,
  ConstString.chat: ConstString.chat,
  ConstString.couponAppliedSuccessfully: ConstString.couponAppliedSuccessfully,
  ConstString.plzEnterValidCoupon: ConstString.plzEnterValidCoupon,
  ConstString.addedToFav: ConstString.addedToFav,
  ConstString.removedFromFav: ConstString.removedFromFav,
  ConstString.selectDepartment: ConstString.selectDepartment,
  ConstString.open: ConstString.open,
  ConstString.close: ConstString.close,
  ConstString.flutterwavePayment: ConstString.flutterwavePayment,
  ConstString.pay: ConstString.pay,
  ConstString.ticketCreatedSuccessfully: ConstString.ticketCreatedSuccessfully,
  ConstString.youMustSelectAstate: ConstString.youMustSelectAstate,
  ConstString.youMustSelectAcountry: ConstString.youMustSelectAcountry,
  ConstString.addressSaved: ConstString.addressSaved,
  ConstString.priorityChanged: ConstString.priorityChanged,
  ConstString.statusChanged: ConstString.statusChanged,
  ConstString.plzCheckInternet: ConstString.plzCheckInternet,
  ConstString.selectCategory: ConstString.selectCategory,
  ConstString.selectSubCategory: ConstString.selectSubCategory,
  ConstString.profileDeletedSuccessfully:
      ConstString.profileDeletedSuccessfully,
  ConstString.selectChildCategory: ConstString.selectChildCategory,
  ConstString.refundReqSuccessful: ConstString.refundReqSuccessful,
  ConstString.orderPlacedSuccessfully: ConstString.orderPlacedSuccessfully,
  ConstString.failedToMakePaymentStatusSuccess:
      ConstString.failedToMakePaymentStatusSuccess,
  ConstString.changePriority: ConstString.changePriority,
  ConstString.changeStatus: ConstString.changeStatus,
  ConstString.otpDidntMatch: ConstString.otpDidntMatch,
  ConstString.otpFailedToSend: ConstString.otpFailedToSend,
  ConstString.invalidEmailOrPass: ConstString.invalidEmailOrPass,
  ConstString.somethingWentWrong: ConstString.somethingWentWrong,
  ConstString.userLoggedOut: ConstString.userLoggedOut,
  ConstString.removedFromCart: ConstString.removedFromCart,
  ConstString.profileUpdatedSuccessfully:
      ConstString.profileUpdatedSuccessfully,
  ConstString.registrationSuccessful: ConstString.registrationSuccessful,
  ConstString.otpSendFailed: ConstString.otpSendFailed,
  ConstString.youEnteredOtpCorrectButSomethingWrong:
      ConstString.youEnteredOtpCorrectButSomethingWrong,
  ConstString.passChangedSuccessfully: ConstString.passChangedSuccessfully,
  ConstString.makeSureRepeatedPassCorrectly:
      ConstString.makeSureRepeatedPassCorrectly,
  ConstString.createAccountWithTheseDetails:
      ConstString.createAccountWithTheseDetails,
  ConstString.pressAgainToExit: ConstString.pressAgainToExit,
  ConstString.clickToSee: ConstString.clickToSee,
  ConstString.cashOnDelivery: ConstString.cashOnDelivery,
  ConstString.youMustSelectAPaymentMethod:
      ConstString.youMustSelectAPaymentMethod,
  ConstString.youMustSelectACity: ConstString.youMustSelectACity,
  ConstString.selectState: ConstString.selectState,
  ConstString.searchCity: ConstString.searchCity,
  ConstString.requestRefund: ConstString.requestRefund,
  ConstString.youMustSelectAPaymentMethod:
      ConstString.youMustSelectAPaymentMethod,
  ConstString.youMustSelectAPaymentMethod:
      ConstString.youMustSelectAPaymentMethod,
};
